name: Continuous Integration/ Continuous Deployment
on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: tibildocker
        password: T1b1l@docker
          #env:
          #DOCKER_USER: ${{secrets.DOCKER_USER}}
          # DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          #run:
          #docker login -u tibildocker -p T1b1l@docker

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: tibildocker/ingest-ms:latest

          #- name: Docker Push
          #env:
          #REPO: ingest-ms
          #run: |
          #docker build -t $REPO .
          #docker tag $REPO:latest tibildocker/$REPO:latest
          #docker push tibildocker/$REPO

    - name: Docker pull image and deploy from hub
      runs-on: ubuntu-latest
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        REPO: ingest-ms
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker login
          docker pull tibildocker/ingest-ms
          docker stop ingest_app || true
          docker rm ingest_app || true
          docker run -d --name ingest_app -p 3001:3001 tibildocker/ingest-ms
