name: Continuous Integration/ Continuous Deployment
on:
  pull_request_target:
    types:
      - closed
    branches: [main]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: adding aws cred
      run: sed -i 's|"access_key_id"|"${{secrets.ACCESS_KEY}}"|g;s|"secret_key_id"|"${{secrets.SECRET_KEY}}"|g' index.js
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./dev.Dockerfile
        push: true
        tags: tibildocker/ingest-ms:1

    - name: Docker pull image and deploy from
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        REPO: ingest-ms
        host: 35.154.229.40
      uses: appleboy/ssh-action@master
      with:
        HOST: "$host"
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        PORT: '22'
        script: |
          docker login
          docker pull tibildocker/ingest-ms
          docker stop ingest_app || true
          docker rm ingest_app || true
          docker rmi ingest-ms:latest || true
          docker run -d --name ingest_app -p 3000:3000 tibildocker/ingest-ms
